name: Dart Code Checks

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request: {}

jobs:
  install:
    name: 游닌 Install dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: "stable"
      - run: flutter --version
      - name: 游닌 Install dependencies
        run: flutter pub get

  format:
    name: 游빛 Format code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: "stable"
      - run: flutter --version
      - name: 游닌 Install dependencies
        run: flutter pub get
      - name: 丘뉦잺 Verify formatting
        run: dart format --output=none --set-exit-if-changed .

  analyze:
    name: 游댧 Analyze code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: "stable"
      - run: flutter --version
      - name: 游닌 Install dependencies
        run: flutter pub get
      - name: 游댧 Analyze project source
        run: flutter analyze --fatal-infos

  test:
    name: 游빍 Run tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: "stable"
      - run: flutter --version
      - name: 游닌 Install dependencies
        run: flutter pub get
      - name: 游빍 Run tests
        run: flutter test
