name: Dart Code Checks

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request: {}

jobs:
  install:
    name: ğŸ“¥ Install dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: "stable"
      - run: flutter --version
      - name: ğŸ“¥ Install dependencies
        run: flutter pub get

  format:
    name: ğŸ§¹ Format code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: "stable"
      - run: flutter --version
      - name: ğŸ“¥ Install dependencies
        run: flutter pub get
      - name: âš’ï¸ Verify formatting
        run: dart format --output=none --set-exit-if-changed .

  analyze:
    name: ğŸ”¬ Analyze code
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.9"
          channel: "stable"
      - run: flutter --version
      - name: ğŸ“¥ Install dependencies
        run: flutter pub get
      - name: ğŸ”¬ Analyze project source
        run: flutter analyze --fatal-infos

